# Generated by Django 4.2.7 on 2023-11-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balanceBTC',
            new_name='balance_btc',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='balanceCLP',
            new_name='balance_clp',
        ),
    ]
