# Generated by Django 4.2.7 on 2023-12-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_rename_balancebtc_wallet_balance_btc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance_btc',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance_clp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
